# --- !Ups

-- TODO: Insert foreign keys. I need other tables to do so.
CREATE TABLE "Messages" (
  "message" VARCHAR NOT NULL,
  "toUserId" BIGINT NOT NULL, 
  "fromUserId" BIGINT NOT NULL, 
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);

CREATE TABLE "Transactions" (
  "storageTaken" INT NOT NULL,
  "fromDate" TIMESTAMP NOT NULL,
  "toDate" TIMESTAMP NOT NULL,
  "timestamp" TIMESTAMP NOT NULL,
  "postingId" BIGINT NOT NULL,
  "buyerUserId" BIGINT NOT NULL, 
  "fromUserId" BIGINT NOT NULL, 
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);

CREATE TABLE "User" (
  "userID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "email" VARCHAR NOT NULL,
  "verifiedEmail" VARCHAR,
  "universityID" BIGINT NOT NULL,
  "thumbnail" VARCHAR,
  "creationTime" BIGINT NOT NULL,
  "lastLogin" BIGINT);

# --- !Downs

DROP TABLE "Messages";
DROP TABLE "Transactions";
DROP TABLE "User";
